Require mocha/minitest instead of mocha/mini_test
Mocha is throwing a LoadError:

> LoadError: cannot load such file -- mocha/mini_test

Require mocha/minitest instead of mocha/mini_test to fix this.

At the same time there is a deprecation warning:

> Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of
'mocha/setup'.

Remove mocha/setup to solve this.